### ISSUE TITLE
terminal-table 1.4.5 has spec failures

### ISSUE THREAD

**Issue by graaff** [tj/terminal-table#33]
With ruby 1.9.3p429 (2013-05-15 revision 40747) [x86_64-linux] I'm seeing these failures: 

```
  1) Terminal::Table should account for the colspan when selecting columns
     Failure/Error: @table.column_with_headings(1).should == [2,"4,5"]
       expected: [2, "4,5"]
            got: [2, 6] (using ==)
     # ./spec/table_spec.rb:31:in `block (2 levels) in <module:Terminal>'

  2) Terminal::Table should only increase column size for multi-column if it is unavoidable
     Failure/Error: EOF
       expected: "+-------+---+---+\n| 12345 | 2 | 3 |\n| 123456789 | 4 |\n+-------+---+---+"
            got: "+-------+-----+---+\n| 12345 | 2   | 3 |\n| 123456789   | 4 |\n+-------+-----+---+" (using ==)
       Diff:
       @@ -1,5 +1,5 @@
       -+-------+---+---+
       -| 12345 | 2 | 3 |
       -| 123456789 | 4 |
       -+-------+---+---+
       ++-------+-----+---+
       +| 12345 | 2   | 3 |
       +| 123456789   | 4 |
       ++-------+-----+---+
     # ./spec/table_spec.rb:429:in `block (2 levels) in <module:Terminal>'

```

**Comment by nateberkopec** [comment]
:+1: I'm seeing these as well. Working on it, but PR's welcome.

**Comment by nateberkopec** [comment]
Only one spec failure remaining in 1.7.0: "Terminal::Table should only increase column size for multi-column if it is unavoidable."

**Comment by graaff** [comment]
Fix confirmed (on more modern versions of ruby :-) ), thanks so far!
