### ISSUE TITLE
colspan causes align_column to fail

### ISSUE THREAD

**Issue by dennisjbell** [tj/terminal-table#35]
````
> t = Terminal::Table.new(rows: [['name',{value:'values',colspan:2}],['test',1,2]]);
> t.align_column(2,:right)

NoMethodError: undefined method `alignment?' for nil:NilClass
from /Users/dbell/.rvm/gems/ruby-1.9.3-p429@cater/gems/terminal-table-1.4.5/lib/terminal-table/table.rb:27:in `block in align_column'
  /Users/dbell/.rvm/gems/ruby-1.9.3-p429@cater/gems/terminal-table-1.4.5/lib/terminal-table/table.rb:25:in `each'
  /Users/dbell/.rvm/gems/ruby-1.9.3-p429@cater/gems/terminal-table-1.4.5/lib/terminal-table/table.rb:25:in `each_with_index'
  /Users/dbell/.rvm/gems/ruby-1.9.3-p429@cater/gems/terminal-table-1.4.5/lib/terminal-table/table.rb:25:in `align_column'
````

**Comment by nateberkopec** [comment]
Fixed at some point - not sure when.
